### ISSUE TITLE
Installation fails on Craft 3.7.6

### ISSUE THREAD

**Issue by brycekirk** [vaersaagod/dospaces#24]
The following error shows, and installation fails `Installation request for guzzlehttp/psr7 (locked at 2.0.0) -> satisfiable by guzzlehttp/psr7[2.0.0].`

**Comment by AugustMiller** [comment]
This appears to be an issue with the underlying AWS SDK: aws/aws-sdk-php#2329

**Comment by aelvan** [comment]
Another thread here: https://github.com/aws/aws-sdk-php/issues/2264
Fixed by this PR which is waiting to be released: https://github.com/aws/aws-sdk-php/pull/2276

For now, use `composer require -W vaersaagod/dospaces` when installing, it'll try to downgrade packages until all dependencies are met (which is possible still).

Keeping this open until the fix has been released.

**Comment by rjgux** [comment]
Thanks @aelvan!

**Comment by AugustMiller** [comment]
Looks like this was released! 🎉

**Comment by aelvan** [comment]
Yes, it was finally released. Closing.
